from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75
_C.DRUG.PADDING = True
_C.DRUG.LAYERS = 1
_C.DRUG.NUM_HEAD = 8
_C.DRUG.HIDDEN_LAYERS = [256, 256, 256]
_C.DRUG.NODE_IN_EMBEDDING = 256
_C.DRUG.MAX_NODES = 290

# Protein feature extractor
_C.PROTEIN = CN()
_C.PROTEIN.LAYERS = 1
_C.PROTEIN.EMBEDDING_DIM = 256
_C.PROTEIN.NUM_HEAD = 8
_C.PROTEIN.PADDING = True

#DRUG-TARGET DIM
_C.MGN = CN()
_C.MGN.EMBEDDING_DIM = 256

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "MLP"
_C.DECODER.IN_DIM = 512
_C.DECODER.HIDDEN_DIM = 128
_C.DECODER.OUT_DIM = 32
_C.DECODER.BINARY = 2

# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 50
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.NUM_WORKERS = 0
_C.SOLVER.LR = 0.0001
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.5
_C.SOLVER.DECAY_INTERVAL = 20
_C.SOLVER.WEIGHT_DECAY = 1e-5
_C.SOLVER.SEED = 42

# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"../output/result/"
_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()
